name: postek_printer_plugin_example
description: "Demonstrates how to use the postek_printer_plugin plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  postek_printer_plugin:
    path: ../

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true